
[terminal.shell]
program = "/bin/bash"
args = ["-l"]

[window]
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = true 
decorations = "Full"
opacity = 1.0
blur = false

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
size = 13
builtin_box_drawing = true 

[bell]
animation = "Linear"
command = { program = "pw-play", args = ["/usr/share/sounds/gnome/default/alerts/string.ogg"] }

[cursor]
style = { shape = "Beam", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]

[general]
live_config_reload = true

import = []

[terminal]
